name: John Calabro
favicon: null
layout_spectrum: 0.3582037123851478
typography_spectrum: 0.431567374849692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07489993656054139
  lightness: 0.5878017116338015
  saturation: 0.8733219073619694
  rhythmicContrast: 0.3682649196125567
purpose: []
